export const userActionTypes = {
  BOOKING_REQUEST: "BOOKING_REQUEST",
  BOOKING_SUCCESS: "BOOKING_SUCCESS",
  BOOKING_FAILURE: "BOOKING_FAILURE",

  GET_LIST_BOOKING_REQUEST: "GET_LIST_BOOKING_REQUEST",
  GET_LIST_BOOKING_SUCCESS: "GET_LIST_BOOKING_SUCCESS",
  GET_LIST_BOOKING_FAILURE: "GET_LIST_BOOKING_FAILURE",
};
